#!/usr/bin/env python3
"""Generates the Swift, Kotlin and JS scheme tables from data/schemes. Run after editing anything there."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
schemes = [json.loads(p.read_text()) for p in sorted((root / "data/schemes").glob("*.json"))]
TABLES = ["vowels", "compounds", "consonants", "modifiers", "finals", "nasal"]

KOTLIN_OUT = root / "android/src/main/kotlin/com/kevinissac/transliterationkit/SchemeData.kt"
SWIFT_OUT = root / "Sources/TransliterationKit/SchemeData.swift"
JS_OUT = root / "js/src/schemes.js"
HEADER = "Generated by tools/generate.py from data/schemes — do not edit by hand."


def utf16(s):
    b = s.encode("utf-16-le")
    return [int.from_bytes(b[i:i + 2], "little") for i in range(0, len(b), 2)]


def kt(s):
    """Escapes everything outside printable ASCII so no editor or normaliser can alter a key."""
    out = ""
    for u in utf16(s):
        c = chr(u)
        if c in '"\\$':
            out += "\\" + c
        elif 0x20 <= u < 0x7F:
            out += c
        else:
            out += f"\\u{u:04X}"
    return f'"{out}"'


def sw(s):
    out = ""
    for c in s:
        if c in '"\\':
            out += "\\" + c
        elif 0x20 <= ord(c) < 0x7F:
            out += c
        else:
            out += f"\\u{{{ord(c):X}}}"
    return f'"{out}"'


def js(s):
    return json.dumps(s, ensure_ascii=True)


def kotlin():
    out = [f"// {HEADER}", "package com.kevinissac.transliterationkit", "", "internal object SchemeData {", "",
           "    val all: List<SchemeSpec> = listOf("]
    for s in schemes:
        out.append("        SchemeSpec(")
        out.append(f"            code = {kt(s['code'])},")
        out.append(f"            virama = {kt(s['virama'])},")
        out.append(f"            inherentVowel = {kt(s['inherentVowel'])},")
        out.append(f"            wordFinalViramaVowel = {kt(s['wordFinalViramaVowel'])},")
        for t in TABLES:
            out.append(f"            {t} = listOf(")
            out += [f"                {kt(k)} to {kt(v)}," for k, v in s[t]]
            out.append("            ),")
        out.append("        ),")
    out += ["    )", "}", ""]
    KOTLIN_OUT.parent.mkdir(parents=True, exist_ok=True)
    KOTLIN_OUT.write_text("\n".join(out))


def swift():
    out = [f"// {HEADER}", "", "enum SchemeData {", "", "    static let all: [SchemeSpec] = ["]
    for s in schemes:
        out.append("        SchemeSpec(")
        out.append(f"            code: {sw(s['code'])},")
        out.append(f"            virama: {sw(s['virama'])},")
        out.append(f"            inherentVowel: {sw(s['inherentVowel'])},")
        out.append(f"            wordFinalViramaVowel: {sw(s['wordFinalViramaVowel'])},")
        for i, t in enumerate(TABLES):
            out.append(f"            {t}: [")
            out += [f"                ({sw(k)}, {sw(v)})," for k, v in s[t]]
            out.append("            ]" + ("," if i < len(TABLES) - 1 else ""))
        out.append("        ),")
    out += ["    ]", "}", ""]
    SWIFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_OUT.write_text("\n".join(out))


def javascript():
    out = [f"// {HEADER}", "", "export default {"]
    for s in schemes:
        out.append(f"\t{js(s['code'])}: {{")
        out.append(f"\t\tvirama: {js(s['virama'])},")
        out.append(f"\t\tinherentVowel: {js(s['inherentVowel'])},")
        out.append(f"\t\twordFinalViramaVowel: {js(s['wordFinalViramaVowel'])},")
        for t in TABLES:
            out.append(f"\t\t{t}: {{")
            out += [f"\t\t\t{js(k)}: {js(v)}," for k, v in s[t]]
            out.append("\t\t},")
        out.append("\t},")
    out += ["};", ""]
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.write_text("\n".join(out))


kotlin()
swift()
javascript()
